### ISSUE TITLE
可道云安卓App 自动同步闪退问题

### ISSUE THREAD

**Issue by hudayee** [kalcaddle/kodbox#217]
如题，同步一部分照片后app闪退,后续每次打开app都直接闪退（自动同步开启的状态）。adb logcat查看日志得到以下错误。有什么办法可以规避掉或只能等待后续app更新？
手机型号 小米 12
系统 MIUI14.0.7
``` 
10-24 17:12:10.631 6237 6237 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~Io0FBCK22WtMB-qNqSu8mw==/com.kodcloud.kodbox-nf8Z7oXuw0mGU53lYglBAw==/base.apk"],nativeLibraryDirectories=[/data/app/~~Io0FBCK22WtMB-qNqSu8mw==/com.kodcloud.kodbox-nf8Z7oXuw0mGU53lYglBAw==/lib/arm64, /data/app/~~Io0FBCK22WtMB-qNqSu8mw==/com.kodcloud.kodbox-nf8Z7oXuw0mGU53lYglBAw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
10-24 17:12:10.631 6237 6237 E LoadedApk: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
10-24 17:12:10.631 6237 6237 E LoadedApk: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-24 17:12:10.631 6237 6237 E LoadedApk: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.LoadedApk.createAppFactory(LoadedApk.java:282)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1052)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.LoadedApk.getResources(LoadedApk.java:1387)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6840)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2189)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.os.Handler.dispatchMessage(Handler.java:106)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.os.Looper.loopOnce(Looper.java:210)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.os.Looper.loop(Looper.java:299)
10-24 17:12:10.631 6237 6237 E LoadedApk: at android.app.ActivityThread.main(ActivityThread.java:8123)
10-24 17:12:10.631 6237 6237 E LoadedApk: at java.lang.reflect.Method.invoke(Native Method)
10-24 17:12:10.631 6237 6237 E LoadedApk: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
10-24 17:12:10.631 6237 6237 E LoadedApk: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by kalcaddle** [comment]
系统兼容问题, 下个版本优化.

**Comment by hudayee** [comment]
@kalcaddle 有发版计划吗？预计下次是什么时候？

**Comment by kalcaddle** [comment]
> @kalcaddle 有发版计划吗？预计下次是什么时候？

已修复兼容,下个版本发布. 预计本月内.
